spring: 
    profiles: 
        active:
           - dev
---
server:
  port:8889
spring:
    profiles: dev
    application:
        name: microservicecloud-consumer-user
    http:
      multipart:
        max-file-size: 1000Mb
        max-request-size: 100Mb
eureka:
  client: 
    service-url:
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloudconsumer-user8889
    prefer-ip-address: true     

info:
  app.name: ypp-microservicecloud
  company.name: www.ypp.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$. 
---
server:
  port:8889
spring:
    profiles: test
    application:
        name: microservicecloud-consumer-user
    http:
      multipart:
        max-file-size: 1000Mb 
        max-request-size: 100Mb
eureka:
  client: 
    service-url:
       #defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloudconsumer-user8889
    prefer-ip-address: true     

info:
  app.name: ypp-microservicecloud
  company.name: www.ypp.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$. 