server:
  port: 8889

spring:
  application:
    name: microservicecloud-consumer-user

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
       #defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloudconsumer-user8889
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: ypp-microservicecloud
  company.name: www.ypp.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$